site_name: PyKuda2
site_description: A developer friendly wrapper for kuda API
site_url: https://github.com/

theme:
  name: "material"
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: kuda
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: jennyosato/pykuda2
repo_url: https://github.com/jennyosato/pykuda2
edit_uri: ''

plugins:
  - search
  - mkdocstrings

nav:
  - Introduction: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference:
    - "reference/index.md"
    - "reference/utils.md"
    - "reference/kuda.md"
  - explanation.md

extra_css:
  - stylesheets/extra.css
