class MockedAsyncInstantSettlementServiceTestCase:
    def test_base_url(self):
        ...

    async def test_token(self):
        ...

    async def test_headers(self):
        ...

    async def test_can_create_terminal(self):
        ...

    async def test_can_update_terminal(self):
        ...

    async def test_can_all(self):
        ...

    async def test_can_get_settlement_status(self):
        ...

    async def test_can_log_transaction(self):
        ...

    async def test_can_transactions(self):
        ...


class AsyncInstantSettlementServiceTestCase:
    async def test_can_create_terminal(self):
        ...

    async def test_can_update_terminal(self):
        ...

    async def test_can_all(self):
        ...

    async def test_can_get_settlement_status(self):
        ...

    async def test_can_log_transaction(self):
        ...

    async def test_can_transactions(self):
        ...
