class MockedAsyncAccountTesCase:
    async def test_can_create_virtual_account(self):
        ...

    async def test_can_update_virtual_account(self):
        ...

    async def test_can_get_virtual_accounts(self):
        ...

    async def test_can_get_virtual_account(self):
        ...

    async def test_can_disable_virtual_account(self):
        ...

    async def test_can_enable_virtual_account(self):
        ...

    async def test_can_get_admin_account_balance(self):
        ...

    async def test_can_get_virtual_account_balance(self):
        ...


class AsyncAccountTesCase:
    async def test_can_create_virtual_account(self):
        ...

    async def test_can_update_virtual_account(self):
        ...

    async def test_can_get_virtual_accounts(self):
        ...

    async def test_can_get_virtual_account(self):
        ...

    async def test_can_disable_virtual_account(self):
        ...

    async def test_can_enable_virtual_account(self):
        ...

    async def test_can_get_admin_account_balance(self):
        ...

    async def test_can_get_virtual_account_balance(self):
        ...
