class MockedAsyncCardTestCase:
    async def test_can_request_card(self):
        ...

    async def test_can_get_cards(self):
        ...

    async def test_can_activate_card(self):
        ...

    async def test_can_deactivate_card(self):
        ...

    async def test_can_set_card_limit(self):
        ...

    async def test_can_manage_card_channel(self):
        ...

    async def test_can_change_card_pin(self):
        ...

    async def test_can_block_card(self):
        ...

    async def test_can_unblock_card(self):
        ...


class AsyncCardTestCase:
    async def test_can_request_card(self):
        ...

    async def test_can_get_cards(self):
        ...

    async def test_can_activate_card(self):
        ...

    async def test_can_deactivate_card(self):
        ...

    async def test_can_set_card_limit(self):
        ...

    async def test_can_manage_card_channel(self):
        ...

    async def test_can_change_card_pin(self):
        ...

    async def test_can_block_card(self):
        ...

    async def test_can_unblock_card(self):
        ...
