class MockedAsyncSavingsTestCase:
    async def test_can_create_plain_savings_account(self):
        ...

    async def test_can_get_plain_savings_account(self):
        ...

    async def test_can_get_plain_savings_accounts(self):
        ...

    async def test_can_credit_or_debit_plain_savings_account(self):
        ...

    async def test_can_get_plain_savings_account_transactions(self):
        ...

    async def test_can_create_open_flexible_savings_account(self):
        ...

    async def test_can_pre_create_open_flexible_savings_account(self):
        ...

    async def test_can_get_open_flexible_savings_account(self):
        ...

    async def test_can_get_open_flexible_savings_accounts(self):
        ...

    async def test_can_withdraw_from_flexible_savings_account(self):
        ...

    async def test_can_get_flexible_savings_account_transactions(self):
        ...

    async def test_can_create_fixed_savings_account(self):
        ...

    async def test_can_get_fixed_savings_account(self):
        ...

    async def test_can_get_fixed_savings_accounts(self):
        ...

    async def test_can_close_fixed_savings_account(self):
        ...

    async def test_can_get_fixed_savings_account_transactions(self):
        ...


class AsyncSavingsTestCase:
    async def test_can_create_plain_savings_account(self):
        ...

    async def test_can_get_plain_savings_account(self):
        ...

    async def test_can_get_plain_savings_accounts(self):
        ...

    async def test_can_credit_or_debit_plain_savings_account(self):
        ...

    async def test_can_get_plain_savings_account_transactions(self):
        ...

    async def test_can_create_open_flexible_savings_account(self):
        ...

    async def test_can_pre_create_open_flexible_savings_account(self):
        ...

    async def test_can_get_open_flexible_savings_account(self):
        ...

    async def test_can_get_open_flexible_savings_accounts(self):
        ...

    async def test_can_withdraw_from_flexible_savings_account(self):
        ...

    async def test_can_get_flexible_savings_account_transactions(self):
        ...

    async def test_can_create_fixed_savings_account(self):
        ...

    async def test_can_get_fixed_savings_account(self):
        ...

    async def test_can_get_fixed_savings_accounts(self):
        ...

    async def test_can_close_fixed_savings_account(self):
        ...

    async def test_can_get_fixed_savings_account_transactions(self):
        ...
