class MockedBillingAndBettingTestCase:
    def test_can_get_bill_type_options(self):
        ...

    def test_can_verify_customer_before_purchase(self):
        ...

    def test_can_purchase_bill(self):
        ...

    def test_can_purchase_bill_from_virtual_account(self):
        ...

    def test_can_get_bill_purchase_status(self):
        ...

    def test_can_get_purchased_bills(self):
        ...

    def test_can_get_purchased_bill_from_virtual_account(self):
        ...


class BillingAndBettingTestCase:
    def test_can_get_bill_type_options(self):
        ...

    def test_can_verify_customer_before_purchase(self):
        ...

    def test_can_purchase_bill(self):
        ...

    def test_can_purchase_bill_from_virtual_account(self):
        ...

    def test_can_get_bill_purchase_status(self):
        ...

    def test_can_get_purchased_bills(self):
        ...

    def test_can_get_purchased_bill_from_virtual_account(self):
        ...
