class MockedInstantSettlementServiceTestCase:
    def test_base_url(self):
        ...

    def test_token(self):
        ...

    def test_headers(self):
        ...

    def test_can_create_terminal(self):
        ...

    def test_can_update_terminal(self):
        ...

    def test_can_all(self):
        ...

    def test_can_get_settlement_status(self):
        ...

    def test_can_log_transaction(self):
        ...

    def test_can_transactions(self):
        ...


class InstantSettlementServiceTestCase:
    def test_can_create_terminal(self):
        ...

    def test_can_update_terminal(self):
        ...

    def test_can_all(self):
        ...

    def test_can_get_settlement_status(self):
        ...

    def test_can_log_transaction(self):
        ...

    def test_can_transactions(self):
        ...
