class MockedCardTestCase:
    def test_can_request_card(self):
        ...

    def test_can_get_cards(self):
        ...

    def test_can_activate_card(self):
        ...

    def test_can_deactivate_card(self):
        ...

    def test_can_set_card_limit(self):
        ...

    def test_can_manage_card_channel(self):
        ...

    def test_can_change_card_pin(self):
        ...

    def test_can_block_card(self):
        ...

    def test_can_unblock_card(self):
        ...


class CardTestCase:
    def test_can_request_card(self):
        ...

    def test_can_get_cards(self):
        ...

    def test_can_activate_card(self):
        ...

    def test_can_deactivate_card(self):
        ...

    def test_can_set_card_limit(self):
        ...

    def test_can_manage_card_channel(self):
        ...

    def test_can_change_card_pin(self):
        ...

    def test_can_block_card(self):
        ...

    def test_can_unblock_card(self):
        ...
