class MockedAccountTesCase:
    def test_can_create_virtual_account(self):
        ...

    def test_can_update_virtual_account(self):
        ...

    def test_can_get_virtual_accounts(self):
        ...

    def test_can_get_virtual_account(self):
        ...

    def test_can_disable_virtual_account(self):
        ...

    def test_can_enable_virtual_account(self):
        ...

    def test_can_get_admin_account_balance(self):
        ...

    def test_can_get_virtual_account_balance(self):
        ...


class AccountTesCase:
    def test_can_create_virtual_account(self):
        ...

    def test_can_update_virtual_account(self):
        ...

    def test_can_get_virtual_accounts(self):
        ...

    def test_can_get_virtual_account(self):
        ...

    def test_can_disable_virtual_account(self):
        ...

    def test_can_enable_virtual_account(self):
        ...

    def test_can_get_admin_account_balance(self):
        ...

    def test_can_get_virtual_account_balance(self):
        ...
