
class MockedTransaction:
    def test_can_get_banks(self):
        ...

    def test_can_confirm_transfer_recipient(self):
        ...

    def test_can_fund_transfer(self):
        ...

    def test_can_virtual_account_fund_transfer(self):
        ...

    def test_can_process_transfers(self):
        ...


    def test_can_get_transfer_instructions(self):
        ...

    def test_can_get_transaction_logs(self):
        ...

    def test_can_get_transaction_history(self):
        ...

    def test_can_get_filtered_transaction_history(self):
        ...

    def test_can_get_virtual_account_transaction_history(self):
        ...

    def test_can_get_virtual_account_filtered_transaction_history(self):
        ...

    def test_can_get_status(self):
        ...

    def test_can_fund_virtual_account(self):
        ...

    def test_can_withdraw_from_virtual_account(self):
        ...


class Transaction:
    def test_can_get_banks(self):
        ...

    def test_can_confirm_transfer_recipient(self):
        ...

    def test_can_fund_transfer(self):
        ...

    def test_can_virtual_account_fund_transfer(self):
        ...

    def test_can_process_transfers(self):
        ...

    def test_can_get_transfer_instructions(self):
        ...

    def test_can_get_transaction_logs(self):
        ...

    def test_can_get_transaction_history(self):
        ...

    def test_can_get_filtered_transaction_history(self):
        ...

    def test_can_get_virtual_account_transaction_history(self):
        ...

    def test_can_get_virtual_account_filtered_transaction_history(self):
        ...

    def test_can_get_status(self):
        ...

    def test_can_fund_virtual_account(self):
        ...

    def test_can_withdraw_from_virtual_account(self):
        ...
