class MockedGiftCardTestCase:
    def test_can_gift_cards(self):
        ...

    def test_can_purchase_gift_card(self):
        ...

    def test_can_purchase_gift_card_from_virtual_account(self):
        ...

    def test_can_get_gift_card_status(self):
        ...


class GiftCardTestCase:
    def test_can_gift_cards(self):
        ...

    def test_can_purchase_gift_card(self):
        ...

    def test_can_purchase_gift_card_from_virtual_account(self):
        ...

    def test_can_get_gift_card_status(self):
        ...
